// SPDX-License-Identifier: MIT
// Copyright (C) 2025, Advanced Micro Devices, Inc. All rights reserved.
// Based on code generated by LLM

#include "metrics.h"

#ifndef NOMINMAX
  #define NOMINMAX
#endif
#include <windows.h>
#include <psapi.h>

namespace aiebu {

process_metrics get_process_metrics()
{
  static constexpr unsigned int kilobytes = 1024;
  static constexpr double milliseconds = 1e-4;
  process_metrics met{};
  // Peak memory
  PROCESS_MEMORY_COUNTERS pmc{};
  if (GetProcessMemoryInfo(GetCurrentProcess(), &pmc, sizeof(pmc))) {
    met.m_peak_kb = static_cast<std::uint64_t>(pmc.PeakWorkingSetSize) / kilobytes;
  }

  // CPU times
  FILETIME createFT{}, exitFT{}, kernelFT{}, userFT{};
  if (GetProcessTimes(GetCurrentProcess(), &createFT, &exitFT, &kernelFT, &userFT)) {
    auto filetime_to_seconds = [](const FILETIME& ft) {
      ULARGE_INTEGER uli;
      uli.LowPart  = ft.dwLowDateTime;
      uli.HighPart = ft.dwHighDateTime;
      // FILETIME units: 100-nanosecond intervals
      return static_cast<double>(uli.QuadPart) * milliseconds;
    };
    met.m_cpu_ms  = filetime_to_seconds(kernelFT) + filetime_to_seconds(userFT);
  }
  return met;
}
}
