// SPDX-License-Identifier: MIT
// Copyright (C) 2025, Advanced Micro Devices, Inc. All rights reserved.
// Based on code generated by LLM

#include <sys/resource.h>
#include <sys/time.h>
#include <unistd.h>

#include "metrics.h"

namespace aiebu {
process_metrics get_process_metrics()
{
  static constexpr double milliseconds = 1000;
  static constexpr double microseconds = 1e-3;
  process_metrics met{};
  rusage ru{};
  if (getrusage(RUSAGE_SELF, &ru) != 0)
    return met;

  met.m_peak_kb = static_cast<std::uint64_t>(ru.ru_maxrss);

  met.m_cpu_ms =
    static_cast<double>(ru.ru_utime.tv_sec) * milliseconds +
    static_cast<double>(ru.ru_utime.tv_usec) * microseconds +
    static_cast<double>(ru.ru_stime.tv_sec) * milliseconds +
    static_cast<double>(ru.ru_stime.tv_usec) * microseconds;
  return met;
}
}
